# Generated by Django 4.0.4 on 2022-05-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athletics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Athletics',
                'verbose_name_plural': 'Athletes',
            },
        ),
        migrations.CreateModel(
            name='Boxing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Boxing',
                'verbose_name_plural': 'Boxers',
            },
        ),
        migrations.CreateModel(
            name='Cycling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Cycling',
                'verbose_name_plural': 'Cyclists',
            },
        ),
        migrations.CreateModel(
            name='Team_sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Team_sports',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='User_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Username')),
                ('fname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('pass1', models.CharField(max_length=255, verbose_name='Password')),
                ('pass2', models.CharField(max_length=255, verbose_name='Confirm Your Password')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('document', models.FileField(upload_to='user_peoples/documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Weightlifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Weightlifting',
                'verbose_name_plural': 'Weightlifters',
            },
        ),
        migrations.CreateModel(
            name='Wrestling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Wrestling',
                'verbose_name_plural': 'Wrestlers',
            },
        ),
    ]
